// Preset templates + curated stock library grouped by event type.
export const EVENT_TYPES = [
  { id: "wedding", label: "Wedding" },
  { id: "birthday", label: "Birthday" },
  { id: "baby_shower", label: "Baby Shower" },
  { id: "anniversary", label: "Anniversary" },
  { id: "corporate", label: "Corporate" },
];

// Unsplash photos used by the regional / extra templates below.
const u = (id) => `https://images.unsplash.com/photo-${id}?w=1200&q=80`;
const IMG = {
  // South Indian wedding
  gopuram: u("1582510003544-4d00b7f74220"),
  backwaters: u("1602216056096-3b40cc0c9944"),
  // Anniversary
  heartsBokeh: u("1518199266791-5375a83190b7"),
  goldRings: u("1707831853477-545a84511e57"),
  weddingChairs: u("1522673607200-164d1b6ce486"),
  // Corporate
  conferenceRoom: u("1511578314322-379afb476865"),
  microphone: u("1475721027785-f74eccf877e2"),
  skyscrapers: u("1486406146926-c627a92ad1ab"),
  galaBanquet: u("1519167758481-83f550bb49b3"),
  skyline: u("1477959858617-67f85cf4f1df"),
  // Birthday
  balloons: u("1530103862676-de8c9debad1d"),
  confetti: u("1513151233558-d860c5398176"),
  rainbowCake: u("1464347744102-11db6282f854"),
  pineappleParty: u("1496843916299-590492c751f4"),
};

// Ornate backgrounds drawn for the devotional / Nikah templates (frontend/public/backgrounds).
const ORNATE = (name) => `${process.env.PUBLIC_URL || ""}/backgrounds/${name}.svg`;
const BG = {
  kailash: ORNATE("kailash-indigo"),
  ayodhya: ORNATE("ayodhya-saffron"),
  lotus: ORNATE("lotus-rani"),
  mehndi: ORNATE("mehndi-green"),
  nikah: ORNATE("nikah-emerald"),
  goldenIvory: ORNATE("golden-ivory"),
  bunting: ORNATE("birthday-bunting"),
};

// Public-domain paintings on Wikimedia Commons (Raja Ravi Varma and contemporaries).
const DEITY = {
  shivParvati: "https://upload.wikimedia.org/wikipedia/commons/1/1d/An_Oleograph_of_Shiva%2C_Parvati_and_Nandi_by_Raja_Ravi_Varma.jpg",
  ramSita: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Ramapanchayan%2C_Raja_Ravi_Varma_%28Lithograph%29.jpg/1280px-Ramapanchayan%2C_Raja_Ravi_Varma_%28Lithograph%29.jpg",
  vishnuLakshmi: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Vishnu_Laxmi.jpg",
};

// Deity artwork placed in an arch at the top of the card.
const deityArch = (url) => [
  { id: "deity", url, x_pct: 50, y_pct: 18, w_pct: 24, shape: "arch", rotation: 0, z_index: 1 },
];

export const BACKGROUND_LIBRARY = {
  wedding: [
    "https://images.unsplash.com/photo-1519225421980-715cb0215aed?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njd8MHwxfHNlYXJjaHwxfHxlbGVnYW50JTIwd2VkZGluZyUyMHJlY2VwdGlvbiUyMHRhYmxlJTIwc2V0dGluZ3xlbnwwfHx8fDE3ODM1MDU2MTJ8MA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1710587385270-08f30d66bf31?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njd8MHwxfHNlYXJjaHw0fHxlbGVnYW50JTIwd2VkZGluZyUyMHJlY2VwdGlvbiUyMHRhYmxlJTIwc2V0dGluZ3xlbnwwfHx8fDE3ODM1MDU2MTJ8MA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1619043518800-7f14be467dca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzJ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzaWxrJTIwZmFicmljJTIwYmFja2dyb3VuZHxlbnwwfHx8fDE3ODM1MDU2MjF8MA&ixlib=rb-4.1.0&q=85",
    IMG.gopuram, IMG.backwaters, BG.kailash, BG.ayodhya, BG.lotus, BG.mehndi, BG.nikah,
  ],
  birthday: [
    "https://images.unsplash.com/photo-1741969494307-55394e3e4071?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2OTV8MHwxfHNlYXJjaHw0fHxqb3lmdWwlMjBiaXJ0aGRheSUyMHBhcnR5JTIwZGVjb3JhdGlvbnN8ZW58MHx8fHwxNzgzNTA1NjEyfDA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1531956531700-dc0ee0f1f9a5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2OTV8MHwxfHNlYXJjaHwxfHxqb3lmdWwlMjBiaXJ0aGRheSUyMHBhcnR5JTIwZGVjb3JhdGlvbnN8ZW58MHx8fHwxNzgzNTA1NjEyfDA&ixlib=rb-4.1.0&q=85",
    IMG.balloons, IMG.confetti, IMG.rainbowCake, IMG.pineappleParty, BG.bunting,
  ],
  corporate: [
    IMG.conferenceRoom,
    IMG.microphone,
    IMG.skyscrapers, IMG.galaBanquet, IMG.skyline,
  ],
  baby_shower: [
    "https://images.unsplash.com/photo-1644785421448-e1b038f2381e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1OTN8MHwxfHNlYXJjaHwyfHxiYWJ5JTIwc2hvd2VyJTIwZGVjb3JhdGlvbiUyMG5ldXRyYWx8ZW58MHx8fHwxNzgzNTA1NjIxfDA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1695041713023-c08f364a4ea2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1ODh8MHwxfHNlYXJjaHwzfHxhYnN0cmFjdCUyMHBhcGVyJTIwdGV4dHVyZSUyMHdhcm18ZW58MHx8fHwxNzgzNTA1NjIxfDA&ixlib=rb-4.1.0&q=85",
  ],
  anniversary: [
    "https://images.unsplash.com/photo-1612145463153-e97c1774fe2a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTJ8MHwxfHNlYXJjaHwyfHxsdXh1cnklMjBhbm5pdmVyc2FyeSUyMHBhcnR5fGVufDB8fHx8MTc4MzUwNTYyMXww&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1707831853477-545a84511e57?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTJ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBhbm5pdmVyc2FyeSUyMHBhcnR5fGVufDB8fHx8MTc4MzUwNTYyMXww&ixlib=rb-4.1.0&q=85",
    IMG.heartsBokeh, IMG.weddingChairs, BG.goldenIvory,
  ],
};

export const HERO_BACKGROUNDS = [
  "https://images.unsplash.com/photo-1695041713023-c08f364a4ea2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1ODh8MHwxfHNlYXJjaHwzfHxhYnN0cmFjdCUyMHBhcGVyJTIwdGV4dHVyZSUyMHdhcm18ZW58MHx8fHwxNzgzNTA1NjIxfDA&ixlib=rb-4.1.0&q=85",
  "https://images.unsplash.com/photo-1619043518800-7f14be467dca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzJ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzaWxrJTIwZmFicmljJTIwYmFja2dyb3VuZHxlbnwwfHx8fDE3ODM1MDU2MjF8MA&ixlib=rb-4.1.0&q=85",
];

// Curated photo library — clip-art / portrait style shots users can drop on canvas.
export const PHOTO_LIBRARY = {
  deities: [
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/An_Oleograph_of_Shiva%2C_Parvati_and_Nandi_by_Raja_Ravi_Varma.jpg/600px-An_Oleograph_of_Shiva%2C_Parvati_and_Nandi_by_Raja_Ravi_Varma.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Ramapanchayan%2C_Raja_Ravi_Varma_%28Lithograph%29.jpg/600px-Ramapanchayan%2C_Raja_Ravi_Varma_%28Lithograph%29.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Vishnu_Laxmi.jpg/600px-Vishnu_Laxmi.jpg",
  ],
  temple: [
    "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?w=600&q=80",
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
  ],
  florals: [
    "https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&q=80",
    "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600&q=80",
  ],
};

export const FONT_OPTIONS = [
  { id: "cormorant", label: "Cormorant (serif)", value: "'Cormorant Garamond', serif" },
  { id: "playfair", label: "Playfair (serif)", value: "'Playfair Display', serif" },
  { id: "bodoni", label: "Bodoni (serif)", value: "'Bodoni Moda', serif" },
  { id: "outfit", label: "Outfit (sans)", value: "'Outfit', sans-serif" },
  { id: "dancing", label: "Dancing Script", value: "'Dancing Script', cursive" },
  { id: "vibes", label: "Great Vibes", value: "'Great Vibes', cursive" },
];

export const COLOR_SWATCHES = [
  "#D97757", "#C89F59", "#8A6D3B", "#4A6741", "#2C5F5D",
  "#5B4A8C", "#A03E3E", "#1A1A1A", "#F1E9DB", "#FFFFFF",
];

export const ENVELOPE_STYLES = [
  { id: "none", label: "None (open directly)" },
  { id: "classic", label: "Classic Paper" },
  { id: "indian", label: "Shubh Vivah (gold + red)" },
  { id: "modern", label: "Minimal Modern" },
];

export const EFFECT_OPTIONS = [
  { id: "petals", label: "Falling Rose Petals" },
  { id: "flowers", label: "Floating Flowers" },
  { id: "confetti", label: "Confetti Rain" },
  { id: "sparkles", label: "Golden Sparkles" },
  { id: "bells", label: "Temple Bells (visual)" },
];

// Music preset library — SoundHelix public MP3s (no auth needed, generic music)
// plus placeholder for uploads.
export const MUSIC_PRESETS = [
  { id: "none", label: "No music", url: "" },
  { id: "piano", label: "Ambient Piano", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3" },
  { id: "uplifting", label: "Uplifting", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3" },
  { id: "elegant", label: "Elegant Strings", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3" },
  { id: "cinematic", label: "Cinematic", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3" },
];


// Preset "starter" templates users can pick from.
export const TEMPLATES = [
  {
    id: "wed-classic",
    event_type: "wedding",
    name: "Classic Ivory",
    preview: BACKGROUND_LIBRARY.wedding[0],
    data: {
      title: "Anna & Ethan",
      subtitle: "Together with their families",
      hosts: "request the honor of your presence",
      date_text: "Saturday, the 14th of June, 2026",
      time_text: "Ceremony at 4:00 in the afternoon",
      venue: "The Rosewood Gardens · Napa Valley, CA",
      rsvp: "Kindly reply by May 1st · rsvp@annaandethan.love",
      message: "Two hearts, one journey — join us as we say I do.",
      background_url: BACKGROUND_LIBRARY.wedding[0],
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
    },
  },
  {
    id: "wed-silk",
    event_type: "wedding",
    name: "Silk & Blush",
    preview: BACKGROUND_LIBRARY.wedding[2],
    data: {
      title: "Priya & Arjun",
      subtitle: "Save the Date",
      hosts: "with the blessings of our families",
      date_text: "November 22, 2026",
      time_text: "5:30 PM onwards",
      venue: "Taj Falaknuma Palace · Hyderabad",
      rsvp: "RSVP by Oct 15 · +91 98765 43210",
      message: "A celebration of love, laughter, and forever.",
      background_url: BACKGROUND_LIBRARY.wedding[2],
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  // ---- Wedding · South Indian ----
  {
    id: "wed-gopuram",
    event_type: "wedding",
    style: "South Indian",
    name: "Temple Gopuram",
    preview: IMG.gopuram,
    data: {
      title: "Sravani & Venkat",
      subtitle: "Subha Lagnam",
      hosts: "The Reddy and Rao families invite you",
      date_text: "Sunday, 7 March 2027",
      time_text: "Lagnam at 7:42 PM",
      venue: "Sri Venkateswara Kalyana Vedika · Tirupati",
      rsvp: "RSVP · sravani.venkat@gmail.com",
      message: "Join us under the stars as two families become one. Dinner follows the ceremony.",
      background_url: IMG.gopuram,
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  {
    id: "wed-backwaters",
    event_type: "wedding",
    style: "South Indian",
    name: "Kerala Backwaters",
    preview: IMG.backwaters,
    data: {
      title: "Anjali & Nikhil",
      subtitle: "Are getting married",
      hosts: "Together with our families",
      date_text: "Saturday, 23 January 2027",
      time_text: "Muhurtham 10:30 AM · Sadya to follow",
      venue: "Kumarakom Lake Resort · Kottayam, Kerala",
      rsvp: "RSVP by 31 December · +91 94470 55555",
      message: "A morning by the backwaters, a traditional sadya, and the people we love most.",
      background_url: IMG.backwaters,
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.4,
      envelope_style: "classic",
    },
  },
  // ---- Wedding · Devotional & Nikah ----
  {
    id: "wed-shiv-parvati",
    event_type: "wedding",
    style: "Shiv–Parvati",
    name: "Kailash Blessings",
    preview: BG.kailash,
    data: {
      title: "Gauri & Mahesh",
      subtitle: "Shubh Vivah",
      hosts: "",
      date_text: "Monday, 8 March 2027",
      time_text: "Muhurtham 10:15 AM",
      venue: "Shri Kalyan Mandapam · Varanasi",
      rsvp: "|| Om Namah Shivaya ||",
      message: "As Shiva and Parvati are forever one, we invite you to bless the union of our children.",
      background_url: BG.kailash,
      accent_color: "#D9B45A",
      text_color: "#F3EEDF",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      photos: deityArch(DEITY.shivParvati),
      envelope_style: "indian",
      effects: ["flowers"],
    },
  },
  {
    id: "wed-ram-sita",
    event_type: "wedding",
    style: "Ram–Sita",
    name: "Sitaram Vivah",
    preview: BG.ayodhya,
    data: {
      title: "Janaki & Raghav",
      subtitle: "Shubh Vivah",
      hosts: "",
      date_text: "Sunday, 25 April 2027",
      time_text: "Pheras at 7:30 PM",
      venue: "Ram Bagh Palace · Jaipur",
      rsvp: "|| Shri Sitaram ||",
      message: "With the blessings of Shri Ram and Mata Sita, our families invite you to the wedding of our children.",
      background_url: BG.ayodhya,
      accent_color: "#F2C76E",
      text_color: "#FBF1DD",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      photos: deityArch(DEITY.ramSita),
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  {
    id: "wed-vishnu-lakshmi",
    event_type: "wedding",
    style: "Vishnu–Lakshmi",
    name: "Lakshmi Narayan",
    preview: BG.lotus,
    data: {
      title: "Shreya & Narayan",
      subtitle: "Kalyana Mahotsavam",
      hosts: "",
      date_text: "Friday, 21 May 2027",
      time_text: "Muhurtham 11:05 AM",
      venue: "Sri Lakshmi Narasimha Kalyana Mandapam · Hyderabad",
      rsvp: "|| Om Lakshmi Narayanaya Namah ||",
      message: "May the grace of Lakshmi and Narayan bless this new beginning. Your presence will make it complete.",
      background_url: BG.lotus,
      accent_color: "#E8C66A",
      text_color: "#FBEFF4",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      photos: deityArch(DEITY.vishnuLakshmi),
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  {
    id: "wed-nikah",
    event_type: "wedding",
    style: "Nikah",
    name: "Emerald Nikah",
    preview: BG.nikah,
    data: {
      title: "Ayesha & Imran",
      subtitle: "Nikah Ceremony",
      hosts: "Bismillah ir-Rahman ir-Rahim",
      date_text: "Friday, 15 October 2027",
      time_text: "Nikah after Asr · Walima dinner at 8:00 PM",
      venue: "Taj Krishna · Banjara Hills, Hyderabad",
      rsvp: "RSVP · +91 98490 77777",
      message: "With the grace of Allah, we request the honour of your presence at the Nikah of our beloved children.",
      background_url: BG.nikah,
      accent_color: "#D9B45A",
      text_color: "#F3EEDF",
      heading_font: "'Great Vibes', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  // ---- Wedding · North Indian ----
  {
    id: "wed-mehndi",
    event_type: "wedding",
    style: "North Indian",
    name: "Mehndi Night",
    preview: BG.mehndi,
    data: {
      title: "Mehndi & Sangeet",
      subtitle: "Ishita weds Kabir",
      hosts: "",
      date_text: "Thursday, 25 November 2027",
      time_text: "6:00 PM onwards",
      venue: "The Lawns at Taj Palace · New Delhi",
      rsvp: "Dress code: Festive colours · RSVP +91 98100 33333",
      message: "Henna, dholki and a night full of music before the big day.",
      background_url: BG.mehndi,
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Great Vibes', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      envelope_style: "indian",
      effects: ["flowers"],
    },
  },
  {
    id: "bday-joy",
    event_type: "birthday",
    name: "Confetti Joy",
    preview: BACKGROUND_LIBRARY.birthday[0],
    data: {
      title: "Maya turns 8!",
      subtitle: "You're invited",
      hosts: "Come celebrate with us",
      date_text: "Sunday, April 12th",
      time_text: "3:00 – 6:00 PM",
      venue: "42 Willow Lane · Backyard party",
      rsvp: "RSVP: mom@maya-family.com",
      message: "Cake, games and a whole lot of sparkle.",
      background_url: BACKGROUND_LIBRARY.birthday[0],
      accent_color: "#D97757",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      envelope_style: "modern",
      effects: ["confetti"],
    },
  },
  {
    id: "bday-adult",
    event_type: "birthday",
    name: "Golden Thirty",
    preview: BACKGROUND_LIBRARY.birthday[1],
    data: {
      title: "Three Zero",
      subtitle: "Julia's 30th Birthday",
      hosts: "Cheers to a new decade",
      date_text: "Friday, September 5th",
      time_text: "8:00 PM till late",
      venue: "The Aurora Rooftop · Downtown",
      rsvp: "Text 555-0142 to confirm",
      message: "Cocktails, dancing and dear friends.",
      background_url: BACKGROUND_LIBRARY.birthday[1],
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
    },
  },
  {
    id: "bday-bunting",
    event_type: "birthday",
    name: "Bunting Party",
    preview: BG.bunting,
    data: {
      title: "Kiara turns 7",
      subtitle: "Rainbow birthday party",
      hosts: "",
      date_text: "Sunday, 14 November",
      time_text: "3:30 – 6:30 PM",
      venue: "Clubhouse Lawn · Prestige Shantiniketan",
      rsvp: "RSVP to Neha · +91 98860 44444",
      message: "Face painting, a treasure hunt and the biggest rainbow cake you've ever seen.",
      background_url: BG.bunting,
      accent_color: "#FF6B6B",
      text_color: "#3A2E5C",
      heading_font: "'Dancing Script', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      envelope_style: "modern",
      effects: ["confetti"],
    },
  },
  {
    id: "bday-balloons",
    event_type: "birthday",
    name: "Balloon Bash",
    preview: IMG.balloons,
    data: {
      title: "Aarav is 5!",
      subtitle: "Let's pop some balloons",
      hosts: "Come party with us",
      date_text: "Saturday, 17 July",
      time_text: "4:00 – 7:00 PM",
      venue: "Funky Monkeys Play Centre · Pune",
      rsvp: "RSVP to Riya · +91 98220 11111",
      message: "Games, magic show, cake and a sky full of balloons.",
      background_url: IMG.balloons,
      accent_color: "#FFD166",
      text_color: "#FFFFFF",
      heading_font: "'Dancing Script', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.4,
      envelope_style: "modern",
      effects: ["confetti"],
    },
  },
  {
    id: "bday-sprinkles",
    event_type: "birthday",
    name: "Sweet Sixteen",
    preview: IMG.confetti,
    data: {
      title: "Sweet Sixteen",
      subtitle: "Zara's birthday bash",
      hosts: "You're invited to",
      date_text: "Friday, 10 September",
      time_text: "7:00 PM till late",
      venue: "The Terrace Lounge · Indiranagar",
      rsvp: "Text 98450 22222 to RSVP",
      message: "Music, mocktails and a dance floor waiting for you.",
      background_url: IMG.confetti,
      accent_color: "#FFFFFF",
      text_color: "#FFFFFF",
      heading_font: "'Great Vibes', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.25,
      effects: ["confetti", "sparkles"],
    },
  },
  {
    id: "bday-cake",
    event_type: "birthday",
    name: "Rainbow Cake",
    preview: IMG.rainbowCake,
    data: {
      title: "One Year Old!",
      subtitle: "Little Myra's first birthday",
      hosts: "Join us for cake and smiles",
      date_text: "Sunday, 3 October",
      time_text: "11:00 AM Brunch",
      venue: "Our home · 18 Palm Grove, Chennai",
      rsvp: "RSVP · myra.turns1@gmail.com",
      message: "One whole year of giggles — help us celebrate our little sunshine.",
      background_url: IMG.rainbowCake,
      accent_color: "#FFD166",
      text_color: "#FFFFFF",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
      envelope_style: "classic",
      effects: ["confetti"],
    },
  },
  {
    id: "bday-tropical",
    event_type: "birthday",
    name: "Tropical Fiesta",
    preview: IMG.pineappleParty,
    data: {
      title: "Party Like It's 40",
      subtitle: "Vikram's tropical birthday",
      hosts: "Grab your shades",
      date_text: "Saturday, 22 May",
      time_text: "Sundowner · 5:30 PM",
      venue: "Poolside at The Leela · Goa",
      rsvp: "RSVP · +91 99200 33333",
      message: "Pineapples, piña coladas and a sunset worth celebrating.",
      background_url: IMG.pineappleParty,
      accent_color: "#FFD166",
      text_color: "#FFFFFF",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
      effects: ["confetti"],
    },
  },
  {
    id: "baby-neutral",
    event_type: "baby_shower",
    name: "Soft Neutral",
    preview: BACKGROUND_LIBRARY.baby_shower[0],
    data: {
      title: "Baby on the way",
      subtitle: "A shower for Emma",
      hosts: "Please join us to celebrate",
      date_text: "Saturday, March 8th",
      time_text: "11:00 AM Brunch",
      venue: "The Greenhouse · 12 Oak Street",
      rsvp: "RSVP by Feb 20 · emma.shower@gmail.com",
      message: "Little feet are on the way — come sprinkle love.",
      background_url: BACKGROUND_LIBRARY.baby_shower[0],
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      effects: ["sparkles"],
    },
  },
  {
    id: "anniv-lux",
    event_type: "anniversary",
    name: "Twenty Five",
    preview: BACKGROUND_LIBRARY.anniversary[0],
    data: {
      title: "25 Years",
      subtitle: "Silver Anniversary",
      hosts: "David & Elena invite you",
      date_text: "Saturday, October 18th, 2026",
      time_text: "7:00 PM Dinner & Dancing",
      venue: "The Grand Ballroom · Hotel Fontaine",
      rsvp: "Regrets only · elena@davidandelena.co",
      message: "A quarter century of love — let's raise a glass.",
      background_url: BACKGROUND_LIBRARY.anniversary[0],
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
      envelope_style: "classic",
    },
  },
  {
    id: "anniv-ruby",
    event_type: "anniversary",
    name: "Ruby Forty",
    preview: IMG.heartsBokeh,
    data: {
      title: "Forty Years",
      subtitle: "Ruby Anniversary",
      hosts: "Celebrating Raj & Sunita",
      date_text: "Saturday, 12 June 2027",
      time_text: "7:30 PM Dinner",
      venue: "The Leela Palace · Bengaluru",
      rsvp: "RSVP to their children · +91 98450 44444",
      message: "Forty years of laughter, patience and love. Join us as we honour them.",
      background_url: IMG.heartsBokeh,
      accent_color: "#FAF9F6",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.35,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  {
    id: "anniv-golden",
    event_type: "anniversary",
    name: "Golden Fifty",
    preview: BG.goldenIvory,
    data: {
      title: "50 Golden Years",
      subtitle: "Margaret & Thomas",
      hosts: "Please join us in celebrating",
      date_text: "Sunday, 5 September 2027",
      time_text: "2:00 PM Garden Lunch",
      venue: "Oakridge Country Club · Portland, OR",
      rsvp: "Kindly reply by August 15 · family@golden50.com",
      message: "Half a century together — let's raise a glass to the couple who started it all.",
      background_url: BG.goldenIvory,
      accent_color: "#9A7428",
      text_color: "#3B2A12",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  {
    id: "anniv-sunset",
    event_type: "anniversary",
    name: "Ten Years of Us",
    preview: IMG.weddingChairs,
    data: {
      title: "Ten Years of Us",
      subtitle: "Neha & Sameer",
      hosts: "An evening with our favourite people",
      date_text: "Saturday, 20 March 2027",
      time_text: "6:30 PM · Sundowners",
      venue: "Olive Bar & Kitchen · Bandra, Mumbai",
      rsvp: "RSVP · +91 98200 66666",
      message: "A decade of adventures together. Come celebrate the next one with us.",
      background_url: IMG.weddingChairs,
      accent_color: "#FAF9F6",
      text_color: "#FAF9F6",
      heading_font: "'Dancing Script', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
    },
  },
  {
    id: "corp-summit",
    event_type: "corporate",
    name: "Corporate Summit",
    preview: BACKGROUND_LIBRARY.corporate[0],
    data: {
      title: "Vertex Summit 2026",
      subtitle: "Annual Leadership Conference",
      hosts: "Vertex Labs cordially invites you",
      date_text: "March 3–5, 2026",
      time_text: "Doors open 8:30 AM",
      venue: "The Hilton San Francisco · Financial District",
      rsvp: "Register: vertex.co/summit",
      message: "Bold ideas, bolder people. Join the conversation.",
      background_url: BACKGROUND_LIBRARY.corporate[0],
      accent_color: "#9FD8CB",
      text_color: "#FAF9F6",
      heading_font: "'Outfit', sans-serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.6,
    },
  },
  {
    id: "corp-launch",
    event_type: "corporate",
    name: "Product Launch",
    preview: IMG.skyscrapers,
    data: {
      title: "Meet Nova X",
      subtitle: "Launch Night",
      hosts: "Lumen Technologies invites you",
      date_text: "Thursday, May 13, 2027",
      time_text: "7:00 PM · Live reveal at 8:00",
      venue: "Pier 48 · San Francisco",
      rsvp: "Register: lumen.co/novax",
      message: "Be the first to see what we've been building — demos, drinks and a few surprises.",
      background_url: IMG.skyscrapers,
      accent_color: "#D97757",
      text_color: "#FAF9F6",
      heading_font: "'Outfit', sans-serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
      envelope_style: "modern",
      effects: ["confetti"],
    },
  },
  {
    id: "corp-gala",
    event_type: "corporate",
    name: "Annual Awards Gala",
    preview: IMG.galaBanquet,
    data: {
      title: "Excellence Awards 2026",
      subtitle: "Annual Gala Dinner",
      hosts: "The Leadership Team cordially invites you",
      date_text: "Friday, December 11, 2026",
      time_text: "Black tie · 7:30 PM",
      venue: "The Grand Ballroom · JW Marriott",
      rsvp: "RSVP by November 27 · events@company.com",
      message: "An evening to honour the people who made this year remarkable.",
      background_url: IMG.galaBanquet,
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.6,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  {
    id: "corp-techconf",
    event_type: "corporate",
    name: "Tech Conference",
    preview: IMG.microphone,
    data: {
      title: "DevForward 2027",
      subtitle: "Two days of talks, workshops & demos",
      hosts: "You're invited to",
      date_text: "April 8–9, 2027",
      time_text: "Keynote 9:30 AM",
      venue: "Bangalore International Exhibition Centre",
      rsvp: "Get your pass: devforward.io",
      message: "Hear from the engineers building what's next — and meet the people behind it.",
      background_url: IMG.microphone,
      accent_color: "#9FD8CB",
      text_color: "#FAF9F6",
      heading_font: "'Outfit', sans-serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
    },
  },
  {
    id: "corp-townhall",
    event_type: "corporate",
    name: "Quarterly Town Hall",
    preview: IMG.skyline,
    data: {
      title: "Q4 Town Hall",
      subtitle: "Results, roadmap & recognition",
      hosts: "All hands",
      date_text: "Wednesday, January 20, 2027",
      time_text: "4:00 – 5:30 PM · Drinks after",
      venue: "Level 30 Atrium · Chicago HQ (and on Zoom)",
      rsvp: "Submit questions in advance: intranet/townhall",
      message: "A look back at the quarter and the plan for the year ahead.",
      background_url: IMG.skyline,
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
    },
  },
];

export function templatesForType(type) {
  return TEMPLATES.filter((t) => t.event_type === type);
}

// Public link guests open. PUBLIC_URL carries the GitHub Pages sub-path
// (e.g. /InviteGenerator), which window.location.origin alone drops.
export function shareUrl(shareId) {
  return `${window.location.origin}${process.env.PUBLIC_URL || ""}/i/${shareId}`;
}

// Build a full file URL usable by <img>/<audio> for a stored file path
export function fileUrl(pathOrUrl) {
  if (!pathOrUrl) return "";
  if (pathOrUrl.startsWith("data:") || pathOrUrl.startsWith("http")) return pathOrUrl;
  const backend = process.env.REACT_APP_BACKEND_URL;
  const token = localStorage.getItem("ic_token");
  const qs = token ? `?auth=${encodeURIComponent(token)}` : "";
  return `${backend}/api/files/${pathOrUrl}${qs}`;
}
