// Preset templates + curated stock library grouped by event type.
export const EVENT_TYPES = [
  { id: "wedding", label: "Wedding" },
  { id: "birthday", label: "Birthday" },
  { id: "baby_shower", label: "Baby Shower" },
  { id: "anniversary", label: "Anniversary" },
  { id: "corporate", label: "Corporate" },
];

// Unsplash photos used by the regional / extra templates below.
const u = (id) => `https://images.unsplash.com/photo-${id}?w=1200&q=80`;
const IMG = {
  // South Indian wedding
  kalash: u("1606293926075-69a00dbfde81"),
  gopuram: u("1582510003544-4d00b7f74220"),
  backwaters: u("1602216056096-3b40cc0c9944"),
  // North Indian wedding
  mandapHall: u("1587271407850-8d438ca9fdf2"),
  mehndi: u("1597157639073-69284dc0fdaf"),
  floralMandap: u("1587271636175-90d58cdad458"),
  // Anniversary
  heartsBokeh: u("1518199266791-5375a83190b7"),
  wineToast: u("1519671482749-fd09be7ccebf"),
  sunsetRide: u("1474552226712-ac0f0961a954"),
  // Corporate
  launchConfetti: u("1492684223066-81342ee5ff30"),
  galaBanquet: u("1519167758481-83f550bb49b3"),
  keynoteStage: u("1505373877841-8d25f7d46678"),
  skyline: u("1477959858617-67f85cf4f1df"),
};

export const BACKGROUND_LIBRARY = {
  wedding: [
    "https://images.unsplash.com/photo-1519225421980-715cb0215aed?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njd8MHwxfHNlYXJjaHwxfHxlbGVnYW50JTIwd2VkZGluZyUyMHJlY2VwdGlvbiUyMHRhYmxlJTIwc2V0dGluZ3xlbnwwfHx8fDE3ODM1MDU2MTJ8MA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1710587385270-08f30d66bf31?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njd8MHwxfHNlYXJjaHw0fHxlbGVnYW50JTIwd2VkZGluZyUyMHJlY2VwdGlvbiUyMHRhYmxlJTIwc2V0dGluZ3xlbnwwfHx8fDE3ODM1MDU2MTJ8MA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1619043518800-7f14be467dca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzJ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzaWxrJTIwZmFicmljJTIwYmFja2dyb3VuZHxlbnwwfHx8fDE3ODM1MDU2MjF8MA&ixlib=rb-4.1.0&q=85",
    IMG.kalash, IMG.gopuram, IMG.backwaters, IMG.mandapHall, IMG.mehndi, IMG.floralMandap,
  ],
  birthday: [
    "https://images.unsplash.com/photo-1741969494307-55394e3e4071?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2OTV8MHwxfHNlYXJjaHw0fHxqb3lmdWwlMjBiaXJ0aGRheSUyMHBhcnR5JTIwZGVjb3JhdGlvbnN8ZW58MHx8fHwxNzgzNTA1NjEyfDA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1531956531700-dc0ee0f1f9a5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2OTV8MHwxfHNlYXJjaHwxfHxqb3lmdWwlMjBiaXJ0aGRheSUyMHBhcnR5JTIwZGVjb3JhdGlvbnN8ZW58MHx8fHwxNzgzNTA1NjEyfDA&ixlib=rb-4.1.0&q=85",
  ],
  corporate: [
    "https://images.unsplash.com/photo-1531058020387-3be344556be6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Nzh8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwY29ycG9yYXRlJTIwZXZlbnQlMjBjb25mZXJlbmNlfGVufDB8fHx8MTc4MzUwNTYxMXww&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1561489404-42f13a2f09a2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Nzh8MHwxfHNlYXJjaHw0fHxtaW5pbWFsaXN0JTIwY29ycG9yYXRlJTIwZXZlbnQlMjBjb25mZXJlbmNlfGVufDB8fHx8MTc4MzUwNTYxMXww&ixlib=rb-4.1.0&q=85",
    IMG.launchConfetti, IMG.galaBanquet, IMG.keynoteStage, IMG.skyline,
  ],
  baby_shower: [
    "https://images.unsplash.com/photo-1644785421448-e1b038f2381e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1OTN8MHwxfHNlYXJjaHwyfHxiYWJ5JTIwc2hvd2VyJTIwZGVjb3JhdGlvbiUyMG5ldXRyYWx8ZW58MHx8fHwxNzgzNTA1NjIxfDA&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1695041713023-c08f364a4ea2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1ODh8MHwxfHNlYXJjaHwzfHxhYnN0cmFjdCUyMHBhcGVyJTIwdGV4dHVyZSUyMHdhcm18ZW58MHx8fHwxNzgzNTA1NjIxfDA&ixlib=rb-4.1.0&q=85",
  ],
  anniversary: [
    "https://images.unsplash.com/photo-1612145463153-e97c1774fe2a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTJ8MHwxfHNlYXJjaHwyfHxsdXh1cnklMjBhbm5pdmVyc2FyeSUyMHBhcnR5fGVufDB8fHx8MTc4MzUwNTYyMXww&ixlib=rb-4.1.0&q=85",
    "https://images.unsplash.com/photo-1707831853477-545a84511e57?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTJ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBhbm5pdmVyc2FyeSUyMHBhcnR5fGVufDB8fHx8MTc4MzUwNTYyMXww&ixlib=rb-4.1.0&q=85",
    IMG.heartsBokeh, IMG.wineToast, IMG.sunsetRide,
  ],
};

export const HERO_BACKGROUNDS = [
  "https://images.unsplash.com/photo-1695041713023-c08f364a4ea2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1ODh8MHwxfHNlYXJjaHwzfHxhYnN0cmFjdCUyMHBhcGVyJTIwdGV4dHVyZSUyMHdhcm18ZW58MHx8fHwxNzgzNTA1NjIxfDA&ixlib=rb-4.1.0&q=85",
  "https://images.unsplash.com/photo-1619043518800-7f14be467dca?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzJ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzaWxrJTIwZmFicmljJTIwYmFja2dyb3VuZHxlbnwwfHx8fDE3ODM1MDU2MjF8MA&ixlib=rb-4.1.0&q=85",
];

// Curated photo library — clip-art / portrait style shots users can drop on canvas.
export const PHOTO_LIBRARY = {
  temple: [
    "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?w=600&q=80",
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
  ],
  south_indian: [
    "https://images.unsplash.com/photo-1587271339318-2e78fdf79586?w=600&q=80",
    "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&q=80",
  ],
  couple: [
    "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=600&q=80",
  ],
  florals: [
    "https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&q=80",
    "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600&q=80",
  ],
};

export const FONT_OPTIONS = [
  { id: "cormorant", label: "Cormorant (serif)", value: "'Cormorant Garamond', serif" },
  { id: "playfair", label: "Playfair (serif)", value: "'Playfair Display', serif" },
  { id: "bodoni", label: "Bodoni (serif)", value: "'Bodoni Moda', serif" },
  { id: "outfit", label: "Outfit (sans)", value: "'Outfit', sans-serif" },
  { id: "dancing", label: "Dancing Script", value: "'Dancing Script', cursive" },
  { id: "vibes", label: "Great Vibes", value: "'Great Vibes', cursive" },
];

export const COLOR_SWATCHES = [
  "#D97757", "#C89F59", "#8A6D3B", "#4A6741", "#2C5F5D",
  "#5B4A8C", "#A03E3E", "#1A1A1A", "#F1E9DB", "#FFFFFF",
];

export const ENVELOPE_STYLES = [
  { id: "none", label: "None (open directly)" },
  { id: "classic", label: "Classic Paper" },
  { id: "indian", label: "Shubh Vivah (gold + red)" },
  { id: "modern", label: "Minimal Modern" },
];

export const EFFECT_OPTIONS = [
  { id: "petals", label: "Falling Rose Petals" },
  { id: "flowers", label: "Floating Flowers" },
  { id: "confetti", label: "Confetti Rain" },
  { id: "sparkles", label: "Golden Sparkles" },
  { id: "bells", label: "Temple Bells (visual)" },
];

// Music preset library — SoundHelix public MP3s (no auth needed, generic music)
// plus placeholder for uploads.
export const MUSIC_PRESETS = [
  { id: "none", label: "No music", url: "" },
  { id: "piano", label: "Ambient Piano", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3" },
  { id: "uplifting", label: "Uplifting", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3" },
  { id: "elegant", label: "Elegant Strings", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3" },
  { id: "cinematic", label: "Cinematic", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3" },
];


// Preset "starter" templates users can pick from.
export const TEMPLATES = [
  {
    id: "wed-classic",
    event_type: "wedding",
    name: "Classic Ivory",
    preview: BACKGROUND_LIBRARY.wedding[0],
    data: {
      title: "Anna & Ethan",
      subtitle: "Together with their families",
      hosts: "request the honor of your presence",
      date_text: "Saturday, the 14th of June, 2026",
      time_text: "Ceremony at 4:00 in the afternoon",
      venue: "The Rosewood Gardens · Napa Valley, CA",
      rsvp: "Kindly reply by May 1st · rsvp@annaandethan.love",
      message: "Two hearts, one journey — join us as we say I do.",
      background_url: BACKGROUND_LIBRARY.wedding[0],
      accent_color: "#8A6D3B",
      text_color: "#1A1A1A",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
    },
  },
  {
    id: "wed-silk",
    event_type: "wedding",
    name: "Silk & Blush",
    preview: BACKGROUND_LIBRARY.wedding[2],
    data: {
      title: "Priya & Arjun",
      subtitle: "Save the Date",
      hosts: "with the blessings of our families",
      date_text: "November 22, 2026",
      time_text: "5:30 PM onwards",
      venue: "Taj Falaknuma Palace · Hyderabad",
      rsvp: "RSVP by Oct 15 · +91 98765 43210",
      message: "A celebration of love, laughter, and forever.",
      background_url: BACKGROUND_LIBRARY.wedding[2],
      accent_color: "#A03E3E",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  // ---- Wedding · South Indian ----
  {
    id: "wed-kalyanam",
    event_type: "wedding",
    style: "South Indian",
    name: "Kalyanam",
    preview: IMG.kalash,
    data: {
      title: "Meenakshi & Karthik",
      subtitle: "Subha Muhurtham",
      hosts: "With the blessings of the Almighty and our elders",
      date_text: "Thursday, 11 February 2027",
      time_text: "Muhurtham 9:15 – 10:30 AM",
      venue: "Sri Kapaleeshwarar Kalyana Mandapam · Mylapore, Chennai",
      rsvp: "Kindly bless us with your presence · +91 98400 12345",
      message: "Our families joyfully invite you to the wedding of their children. Lunch will follow the muhurtham.",
      background_url: IMG.kalash,
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
      envelope_style: "indian",
      effects: ["flowers"],
    },
  },
  {
    id: "wed-gopuram",
    event_type: "wedding",
    style: "South Indian",
    name: "Temple Gopuram",
    preview: IMG.gopuram,
    data: {
      title: "Sravani & Venkat",
      subtitle: "Subha Lagnam",
      hosts: "The Reddy and Rao families invite you",
      date_text: "Sunday, 7 March 2027",
      time_text: "Lagnam at 7:42 PM",
      venue: "Sri Venkateswara Kalyana Vedika · Tirupati",
      rsvp: "RSVP · sravani.venkat@gmail.com",
      message: "Join us under the stars as two families become one. Dinner follows the ceremony.",
      background_url: IMG.gopuram,
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  {
    id: "wed-backwaters",
    event_type: "wedding",
    style: "South Indian",
    name: "Kerala Backwaters",
    preview: IMG.backwaters,
    data: {
      title: "Anjali & Nikhil",
      subtitle: "Are getting married",
      hosts: "Together with our families",
      date_text: "Saturday, 23 January 2027",
      time_text: "Muhurtham 10:30 AM · Sadya to follow",
      venue: "Kumarakom Lake Resort · Kottayam, Kerala",
      rsvp: "RSVP by 31 December · +91 94470 55555",
      message: "A morning by the backwaters, a traditional sadya, and the people we love most.",
      background_url: IMG.backwaters,
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.4,
      envelope_style: "classic",
    },
  },
  // ---- Wedding · North Indian ----
  {
    id: "wed-royal-shaadi",
    event_type: "wedding",
    style: "North Indian",
    name: "Royal Shaadi",
    preview: IMG.mandapHall,
    data: {
      title: "Ananya & Rohan",
      subtitle: "Shubh Vivah",
      hosts: "The Sharma & Malhotra families request your presence",
      date_text: "Friday, 26 November 2027",
      time_text: "Baraat 7:00 PM · Pheras 9:30 PM",
      venue: "Umaid Bhawan Palace · Jodhpur, Rajasthan",
      rsvp: "RSVP by 1 November · +91 98110 22222",
      message: "With joy in our hearts, we invite you to celebrate the union of our children.",
      background_url: IMG.mandapHall,
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
      envelope_style: "indian",
      effects: ["petals", "sparkles"],
    },
  },
  {
    id: "wed-mehndi",
    event_type: "wedding",
    style: "North Indian",
    name: "Mehndi Night",
    preview: IMG.mehndi,
    data: {
      title: "Mehndi & Sangeet",
      subtitle: "Ishita weds Kabir",
      hosts: "Come dance with us",
      date_text: "Thursday, 25 November 2027",
      time_text: "6:00 PM onwards",
      venue: "The Lawns at Taj Palace · New Delhi",
      rsvp: "Dress code: Festive colours · RSVP +91 98100 33333",
      message: "Henna, dholki and a night full of music before the big day.",
      background_url: IMG.mehndi,
      accent_color: "#E7C77D",
      text_color: "#FAF9F6",
      heading_font: "'Great Vibes', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
      envelope_style: "indian",
      effects: ["flowers"],
    },
  },
  {
    id: "wed-floral-mandap",
    event_type: "wedding",
    style: "North Indian",
    name: "Phoolon ka Mandap",
    preview: IMG.floralMandap,
    data: {
      title: "Pooja & Aditya",
      subtitle: "Shubh Vivaah",
      hosts: "With the blessings of our elders",
      date_text: "Sunday, 14 February 2027",
      time_text: "Varmala 11:00 AM · Pheras 12:30 PM",
      venue: "ITC Rajputana · Jaipur",
      rsvp: "Kindly confirm by 20 January · pooja.aditya@gmail.com",
      message: "A daytime celebration among the flowers — we would love you to be part of it.",
      background_url: IMG.floralMandap,
      accent_color: "#A03E3E",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
      envelope_style: "indian",
      effects: ["petals"],
    },
  },
  {
    id: "bday-joy",
    event_type: "birthday",
    name: "Confetti Joy",
    preview: BACKGROUND_LIBRARY.birthday[0],
    data: {
      title: "Maya turns 8!",
      subtitle: "You're invited",
      hosts: "Come celebrate with us",
      date_text: "Sunday, April 12th",
      time_text: "3:00 – 6:00 PM",
      venue: "42 Willow Lane · Backyard party",
      rsvp: "RSVP: mom@maya-family.com",
      message: "Cake, games and a whole lot of sparkle.",
      background_url: BACKGROUND_LIBRARY.birthday[0],
      accent_color: "#D97757",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.45,
      envelope_style: "modern",
      effects: ["confetti"],
    },
  },
  {
    id: "bday-adult",
    event_type: "birthday",
    name: "Golden Thirty",
    preview: BACKGROUND_LIBRARY.birthday[1],
    data: {
      title: "Three Zero",
      subtitle: "Julia's 30th Birthday",
      hosts: "Cheers to a new decade",
      date_text: "Friday, September 5th",
      time_text: "8:00 PM till late",
      venue: "The Aurora Rooftop · Downtown",
      rsvp: "Text 555-0142 to confirm",
      message: "Cocktails, dancing and dear friends.",
      background_url: BACKGROUND_LIBRARY.birthday[1],
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
    },
  },
  {
    id: "baby-neutral",
    event_type: "baby_shower",
    name: "Soft Neutral",
    preview: BACKGROUND_LIBRARY.baby_shower[0],
    data: {
      title: "Baby on the way",
      subtitle: "A shower for Emma",
      hosts: "Please join us to celebrate",
      date_text: "Saturday, March 8th",
      time_text: "11:00 AM Brunch",
      venue: "The Greenhouse · 12 Oak Street",
      rsvp: "RSVP by Feb 20 · emma.shower@gmail.com",
      message: "Little feet are on the way — come sprinkle love.",
      background_url: BACKGROUND_LIBRARY.baby_shower[0],
      accent_color: "#8A6D3B",
      text_color: "#1A1A1A",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.35,
      effects: ["sparkles"],
    },
  },
  {
    id: "anniv-lux",
    event_type: "anniversary",
    name: "Twenty Five",
    preview: BACKGROUND_LIBRARY.anniversary[0],
    data: {
      title: "25 Years",
      subtitle: "Silver Anniversary",
      hosts: "David & Elena invite you",
      date_text: "Saturday, October 18th, 2026",
      time_text: "7:00 PM Dinner & Dancing",
      venue: "The Grand Ballroom · Hotel Fontaine",
      rsvp: "Regrets only · elena@davidandelena.co",
      message: "A quarter century of love — let's raise a glass.",
      background_url: BACKGROUND_LIBRARY.anniversary[0],
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
      envelope_style: "classic",
    },
  },
  {
    id: "anniv-ruby",
    event_type: "anniversary",
    name: "Ruby Forty",
    preview: IMG.heartsBokeh,
    data: {
      title: "Forty Years",
      subtitle: "Ruby Anniversary",
      hosts: "Celebrating Raj & Sunita",
      date_text: "Saturday, 12 June 2027",
      time_text: "7:30 PM Dinner",
      venue: "The Leela Palace · Bengaluru",
      rsvp: "RSVP to their children · +91 98450 44444",
      message: "Forty years of laughter, patience and love. Join us as we honour them.",
      background_url: IMG.heartsBokeh,
      accent_color: "#FAF9F6",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.35,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  {
    id: "anniv-golden",
    event_type: "anniversary",
    name: "Golden Fifty",
    preview: IMG.wineToast,
    data: {
      title: "50 Golden Years",
      subtitle: "Margaret & Thomas",
      hosts: "Please join us in celebrating",
      date_text: "Sunday, 5 September 2027",
      time_text: "2:00 PM Garden Lunch",
      venue: "Oakridge Country Club · Portland, OR",
      rsvp: "Kindly reply by August 15 · family@golden50.com",
      message: "Half a century together — let's raise a glass to the couple who started it all.",
      background_url: IMG.wineToast,
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Cormorant Garamond', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  {
    id: "anniv-sunset",
    event_type: "anniversary",
    name: "Ten Years of Us",
    preview: IMG.sunsetRide,
    data: {
      title: "Ten Years of Us",
      subtitle: "Neha & Sameer",
      hosts: "An evening with our favourite people",
      date_text: "Saturday, 20 March 2027",
      time_text: "6:30 PM · Sundowners",
      venue: "Olive Bar & Kitchen · Bandra, Mumbai",
      rsvp: "RSVP · +91 98200 66666",
      message: "A decade of adventures together. Come celebrate the next one with us.",
      background_url: IMG.sunsetRide,
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Dancing Script', cursive",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.3,
    },
  },
  {
    id: "corp-summit",
    event_type: "corporate",
    name: "Corporate Summit",
    preview: BACKGROUND_LIBRARY.corporate[0],
    data: {
      title: "Vertex Summit 2026",
      subtitle: "Annual Leadership Conference",
      hosts: "Vertex Labs cordially invites you",
      date_text: "March 3–5, 2026",
      time_text: "Doors open 8:30 AM",
      venue: "The Hilton San Francisco · Financial District",
      rsvp: "Register: vertex.co/summit",
      message: "Bold ideas, bolder people. Join the conversation.",
      background_url: BACKGROUND_LIBRARY.corporate[0],
      accent_color: "#2C5F5D",
      text_color: "#FAF9F6",
      heading_font: "'Outfit', sans-serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.6,
    },
  },
  {
    id: "corp-launch",
    event_type: "corporate",
    name: "Product Launch",
    preview: IMG.launchConfetti,
    data: {
      title: "Meet Nova X",
      subtitle: "Launch Night",
      hosts: "Lumen Technologies invites you",
      date_text: "Thursday, May 13, 2027",
      time_text: "7:00 PM · Live reveal at 8:00",
      venue: "Pier 48 · San Francisco",
      rsvp: "Register: lumen.co/novax",
      message: "Be the first to see what we've been building — demos, drinks and a few surprises.",
      background_url: IMG.launchConfetti,
      accent_color: "#D97757",
      text_color: "#FAF9F6",
      heading_font: "'Outfit', sans-serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.5,
      envelope_style: "modern",
      effects: ["confetti"],
    },
  },
  {
    id: "corp-gala",
    event_type: "corporate",
    name: "Annual Awards Gala",
    preview: IMG.galaBanquet,
    data: {
      title: "Excellence Awards 2026",
      subtitle: "Annual Gala Dinner",
      hosts: "The Leadership Team cordially invites you",
      date_text: "Friday, December 11, 2026",
      time_text: "Black tie · 7:30 PM",
      venue: "The Grand Ballroom · JW Marriott",
      rsvp: "RSVP by November 27 · events@company.com",
      message: "An evening to honour the people who made this year remarkable.",
      background_url: IMG.galaBanquet,
      accent_color: "#C89F59",
      text_color: "#FAF9F6",
      heading_font: "'Bodoni Moda', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.6,
      envelope_style: "classic",
      effects: ["sparkles"],
    },
  },
  {
    id: "corp-techconf",
    event_type: "corporate",
    name: "Tech Conference",
    preview: IMG.keynoteStage,
    data: {
      title: "DevForward 2027",
      subtitle: "Two days of talks, workshops & demos",
      hosts: "You're invited to",
      date_text: "April 8–9, 2027",
      time_text: "Keynote 9:30 AM",
      venue: "Bangalore International Exhibition Centre",
      rsvp: "Get your pass: devforward.io",
      message: "Hear from the engineers building what's next — and meet the people behind it.",
      background_url: IMG.keynoteStage,
      accent_color: "#2C5F5D",
      text_color: "#FAF9F6",
      heading_font: "'Outfit', sans-serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.65,
    },
  },
  {
    id: "corp-townhall",
    event_type: "corporate",
    name: "Quarterly Town Hall",
    preview: IMG.skyline,
    data: {
      title: "Q4 Town Hall",
      subtitle: "Results, roadmap & recognition",
      hosts: "All hands",
      date_text: "Wednesday, January 20, 2027",
      time_text: "4:00 – 5:30 PM · Drinks after",
      venue: "Level 30 Atrium · Chicago HQ (and on Zoom)",
      rsvp: "Submit questions in advance: intranet/townhall",
      message: "A look back at the quarter and the plan for the year ahead.",
      background_url: IMG.skyline,
      accent_color: "#F1E9DB",
      text_color: "#FAF9F6",
      heading_font: "'Playfair Display', serif",
      body_font: "'Outfit', sans-serif",
      overlay_opacity: 0.55,
    },
  },
];

export function templatesForType(type) {
  return TEMPLATES.filter((t) => t.event_type === type);
}

// Public link guests open. PUBLIC_URL carries the GitHub Pages sub-path
// (e.g. /InviteGenerator), which window.location.origin alone drops.
export function shareUrl(shareId) {
  return `${window.location.origin}${process.env.PUBLIC_URL || ""}/i/${shareId}`;
}

// Build a full file URL usable by <img>/<audio> for a stored file path
export function fileUrl(pathOrUrl) {
  if (!pathOrUrl) return "";
  if (pathOrUrl.startsWith("data:") || pathOrUrl.startsWith("http")) return pathOrUrl;
  const backend = process.env.REACT_APP_BACKEND_URL;
  const token = localStorage.getItem("ic_token");
  const qs = token ? `?auth=${encodeURIComponent(token)}` : "";
  return `${backend}/api/files/${pathOrUrl}${qs}`;
}
